nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Nelmio bundle workshop
            description: This is an awesome bundle for api docs!
            version: 1.0.0